version: '2'
services:
    db:
        image: postgres:9.5
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - pg_data:/var/lib/postgresql/data
    odoo:
        extends:
            file: odoo-common.yml
            service: odoo_base
        depends_on:
            - db
        ports:
            - "8069:8069"
            - "8072:8072"
    odoo_in:
        extends:
            file: odoo-common.yml
            service: odoo_base
        # command: /bin/bash
        depends_on:
            - db
    odoo_prod:
        extends:
            file: odoo-common.yml
            service: odoo_base
        # command: /bin/bash
        restart: always
        depends_on:
            - db
volumes:
    pg_data:
    odoo_data:
